# Tarea 1 
## Explorando un DataFrame

In [30]:
import pandas as pd
df= pd.read_csv("peliculas.csv")
df.head(1)

,id,titulo,fecha_estreno,genero,duracion_min,presupuesto_musd,taquilla_musd,popularidad,rating,votos,idioma_original,adulto
0,1711051,100 Years,2099-12-31,Sin género,0,0.0,0.0,0.26,0.0,0,en,False

1. ¿Cuántas películas hay en el dataset?

In [11]:
df.shape[0]

100

Por lo tanto, el dataset contiene 100 películas.

2. ¿Cuántas variables o columnas tiene el dataset?

In [12]:
df.shape[1]

12

El DataFrame contiene 12 variables o columnas.

3. ¿Cuáles son las columnas que contiene el DataFrame?

In [13]:
df.columns

Index(['id', 'titulo', 'fecha_estreno', 'genero', 'duracion_min',
       'presupuesto_musd', 'taquilla_musd', 'popularidad', 'rating', 'votos',
       'idioma_original', 'adulto'],
      dtype='object')

Al usar `df.columns`podemos ver en forma de lista los nombres de todas las columnas.

4. ¿Qué tipo de dato tiene cada columna?

In [15]:
df.dtypes

id                    int64
titulo               object
fecha_estreno        object
genero               object
duracion_min          int64
presupuesto_musd    float64
taquilla_musd       float64
popularidad         float64
rating              float64
votos                 int64
idioma_original      object
adulto                 bool
dtype: object

Tenemos que `int64` representa números enteros, `float64`números con decimales, `object` representa texto normalmente y `bool`representa valores verdaderos o falsos.

5. ¿Existen valores faltantes en el dataset?

In [16]:
df.isnull().sum()

id                  0
titulo              0
fecha_estreno       0
genero              0
duracion_min        0
presupuesto_musd    0
taquilla_musd       0
popularidad         0
rating              0
votos               0
idioma_original     0
adulto              0
dtype: int64

Podemos ver que tods las columnas tienen 0 valores nulos, por lo tanto, no existen valores faltantes en el dataset.

6. ¿Cuánta información contiene cada columna?

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                100 non-null    int64
 1   titulo            100 non-null    object
 2   fecha_estreno     100 non-null    object
 3   genero            100 non-null    object
 4   duracion_min      100 non-null    int64
 5   presupuesto_musd  100 non-null    float64
 6   taquilla_musd     100 non-null    float64
 7   popularidad       100 non-null    float64
 8   rating            100 non-null    float64
 9   votos             100 non-null    int64
 10  idioma_original   100 non-null    object
 11  adulto            100 non-null    bool
dtypes: bool(1), float64(4), int64(3), object(4)
memory usage: 8.8+ KB

El DataFrame tiene 100 registros, y todas las columnas contienen 100 valores no nulos. Esto confirma que ninguna columna tiene datos faltantes.

7. ¿Qué columnas contienen información númerica?

In [23]:
df.select_dtypes("number").columns

Index(['id', 'duracion_min', 'presupuesto_musd', 'taquilla_musd',
       'popularidad', 'rating', 'votos'],
      dtype='object')

Ahora sabemos que tenemos 7 columnas con información númerica.

8. ¿Qué columnas contienen información categórica o textual?

In [26]:
df.select_dtypes(["object", "bool"]).columns

Index(['titulo', 'fecha_estreno', 'genero', 'idioma_original', 'adulto'], dtype='object')

De igual manera, ahora sabemos que columnas fueron almacenadas como texto, mientras que `adulto` es una variable booleana (`True`o `False`).

9. Obtén únicamente la columna que contiene el título de las películas.

In [27]:
df["titulo"]

0             100 Years
1       American Static
2             September
3           Light Years
4               Harvest
            ...
95      Batman: Parte 2
96              Золушка
97         Heart Eyes 2
98    Murder, She Wrote
99       Endless Summer
Name: titulo, Length: 100, dtype: object

Así devuleve solamente la columna de `título`.

10. Obtén únicamente la columna que contiene el rating de las películas.

In [28]:
df["rating"]

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
     ...
95    0.0
96    0.0
97    0.0
98    0.0
99    0.0
Name: rating, Length: 100, dtype: float64

Devuelve únicamente el rating de las películas

11. Obtén unicamente las columnas correspondientes al título, género y rating.

In [31]:
df[["titulo","genero","rating"]]

               titulo           genero  rating
0           100 Years       Sin género     0.0
1     American Static  Ciencia ficción     0.0
2           September           Terror     0.0
3         Light Years       Sin género     0.0
4             Harvest           Terror     0.0
..                ...              ...     ...
95    Batman: Parte 2         Misterio     0.0
96            Золушка       Sin género     0.0
97       Heart Eyes 2           Terror     0.0
98  Murder, She Wrote         Misterio     0.0
99     Endless Summer            Drama     0.0

[100 rows x 3 columns]

De sta forma obtenemos un nuevo DataFrame solamente con las tres variables solicitadas.

12. Obtén las estadísticas descriptivas de las variables númericas.

In [32]:
df.describe()

,id,duracion_min,presupuesto_musd,taquilla_musd,popularidad,rating,votos
count,1.000000e+02,100.000000,100.0000,100.0,100.000000,100.0,100.0
mean,1.479390e+06,21.730000,8.1805,0.0,1.385000,0.0,0.0
std,3.080932e+05,50.850316,29.3839,0.0,2.069646,0.0,0.0
min,2.165270e+05,0.000000,0.0000,0.0,0.010000,0.0,0.0
25%,1.363082e+06,0.000000,0.0000,0.0,0.320000,0.0,0.0
50%,1.582366e+06,0.000000,0.0000,0.0,0.640000,0.0,0.0
75%,1.712100e+06,0.000000,0.0000,0.0,1.645000,0.0,0.0
max,1.752779e+06,186.000000,190.0000,0.0,14.950000,0.0,0.0

Podemos ver datos como la duración máxima, o los  valores de algunas variables.

13. ¿Cuál es el rating promedio de las películas?

In [33]:
df["rating"].mean()

np.float64(0.0)

Esto sucede porque las 100 películas tienen actualmente un rating igual a cero.

14. ¿Cuál es la duración promedio de las películas?

In [35]:
df["duracion_min"].mean()

np.float64(21.73)

La duración promedio registrada es de 21.73 minutos, incluyendo las que tienen duración de 0 minutos.

15. ¿Cuál es la película con mayor duración?

In [37]:
df.groupby("titulo")[["duracion_min"]].max().sort_values(by="duracion_min",ascending=False).head(1)

                 duracion_min
titulo
American Static           186

La película con mayor duración es American Static , con 186 minutos.

16. ¿Cuál es la película con mayor rating?

In [38]:
df.groupby("titulo")[["rating"]].max().sort_values(by="rating",ascending=False).head(1)

           rating
titulo
100 Years     0.0

Todas las películas estan empatadas. Devuelve `100 Years` porque es la primera película del DataFrame, no porque tenga un rating mayor que las demás.

17. ¿Cuál es la película que recibió mas votos?

In [39]:
df.groupby("titulo")[["votos"]].max().sort_values(by="votos",ascending=False).head(1)

           votos
titulo
100 Years      0

Al igual que con el rating, todas las películas tienen 0 votos, por lo que estan empatadas y devuelve el primer registro.

18. ¿Qué géneros aparecen en el dataset y cuántas películas hay de cada género?

In [44]:
df.groupby("genero")[["titulo"]].count().sort_values(by="titulo",ascending=False)

                 titulo
genero
Drama                16
Terror               15
Animación            14
Sin género           12
Acción                9
Ciencia ficción       6
Crimen                6
Fantasía              5
Aventura              4
Comedia               2
Documental            2
Familia               2
Misterio              2
Suspense              2
Bélica                1
Historia              1
Romance               1

Aquí tenemos los géneros que hay en el dataset y de mayor a menor cuántas películas hay por cada género.

19. ¿Qué país aparece con mayor frecuencia?
El dataset proporcionado no contiene ninguna columna llamada `pais` ni otra columna que indique directamente el país de cada película. Sin embargo, el código quedaría de esta manera:

In [49]:
df.groupby("pais")[["titulo"]].count().sort_values(by="titulo", ascending=False).head(1)

KeyError: 'pais'

20. ¿Qué plataforma tiene más películas? Sucede lo mismo con el caso anterior. El dataset no contiene ninguna variable llamada `plataforma`. Pero de igual manera, el código se vería así:

In [48]:
df.groupby("plataforma")[["titulo"]].count().sort_values(by="titulo", ascending=False).head(1)

KeyError: 'plataforma'

### Reflexión
1. ¿Qué método de Pandas te resulto mas útil? En general creo que los metodos de agregación son los que considero mas prácticos y fáciles de usar, en espcial despues de usar la función de agrupación `.groupby()`.
2. ¿Qué operación te costó mas trabajo? En específico fueron dos, no considero que tengan mucha complejidad pero sí siento que se debe de tener cuidado al usarlas, me refiero a `df.sort_values()` y `.groupby()`, mas que nada en poner correctamente el orden de las variables. 
3. ¿Qué información sobre el dataset descubriste que no esperabas? Con `.groupby()` pude comparar las películas por género y al mismo tiempo usar `.sort_values()`para obtener de manera ordenadas cuantas películas por genero habían.