# Cheatsheet de Pandas

Este manual reúne las principales operaciones de Pandas para trabajar con DataFrames.

En cada sección se incluye:
1. Una explicación breve.
2. El código necesario.
3. Un ejemplo utilizando nuestra base de datos.
4. Una descripción del resultado obtenido.

# 1. Importar Pandas

Pandas es una librería de Python que permite trabajar y analizar datos, principalmente mediante estructuras como los DataFrames.

Para utilizar Pandas primero debemos importar la librería. El alias que normalmente se utiliza es `pd`.

**Código principal:** `import pandas as pd`

In [1]:
import pandas as pd

### Ejemplo con nuestra base de datos

Después de importar Pandas podemos cargar nuestra base de datos y guardarla en un DataFrame llamado `df`.

El resultado es que Pandas queda disponible para utilizar sus funciones y métodos durante todo el análisis.

In [2]:
df = pd.read_csv("base_generica_pandas.csv")
df

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
0   380.79    49  56.4     1    B    Sur  0.294     5   No   Alto
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2   734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3   602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
4   164.46    47  37.4     7    D    Sur  0.737     3   Sí  Medio
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
95  498.86    43  47.7     8    B    Sur  0.459     2   Sí   Bajo
96  527.51    20  44.4     6    C   Este  0.842     2   Sí   Alto
97  433.27    36  30.6     3    D  Norte  0.769     3   Sí   Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
99  116.81    49  56.3     4    B    Sur  0.046     5   Sí   Bajo

[100 rows x 10 columns]

# 2. Cargar una base de datos

Para cargar un archivo CSV utilizamos la función `read_csv()` de Pandas.

La sintaxis general es `pd.read_csv("archivo.csv")`.

**Código principal:** `pd.read_csv("archivo.csv")`

In [3]:
df = pd.read_csv("base_generica_pandas.csv")

### Ejemplo con nuestra base de datos

Nuestro archivo se llama `base_generica_pandas.csv`, por lo que utilizamos `pd.read_csv()` para leerlo y guardarlo en `df`.

El resultado es un DataFrame que contiene todos los registros de nuestra base.

In [4]:
df.head()

     col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
0  380.79    49  56.4     1    B    Sur  0.294     5   No   Alto
1  951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2  734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3  602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
4  164.46    47  37.4     7    D    Sur  0.737     3   Sí  Medio

# 3. Conocer nuestro DataFrame

Antes de analizar los datos es importante conocer la estructura del DataFrame. Pandas proporciona varios comandos para explorarla.

### `head()`

Muestra las primeras filas del DataFrame. Por defecto muestra 5 filas.

**Código principal:** `df.head()`

In [5]:
df.head()

     col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
0  380.79    49  56.4     1    B    Sur  0.294     5   No   Alto
1  951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2  734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3  602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
4  164.46    47  37.4     7    D    Sur  0.737     3   Sí  Medio

### Resultado

El resultado muestra las primeras filas de nuestra base de datos.

### `tail()`

Muestra las últimas filas del DataFrame. Por defecto muestra 5 filas.

**Código principal:** `df.tail()`

In [7]:
df.tail(8)

      col1  col2  col3  col4 col5   col6   col7  col8 col9 col10
92  763.18    37  64.5     9    A   Este  0.524     1   No  Bajo
93  565.66    53  42.3     1    C  Oeste  0.698     5   Sí  Alto
94  773.26    36  68.2     2    C  Norte  0.796     4   Sí  Alto
95  498.86    43  47.7     8    B    Sur  0.459     2   Sí  Bajo
96  527.51    20  44.4     6    C   Este  0.842     2   Sí  Alto
97  433.27    36  30.6     3    D  Norte  0.769     3   Sí  Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí  Bajo
99  116.81    49  56.3     4    B    Sur  0.046     5   Sí  Bajo

### Resultado

El resultado muestra los últimos 8 registros de nuestra base.

### `shape`

El atributo `shape` muestra el tamaño del DataFrame. El primer número corresponde a las filas y el segundo a las columnas.

**Código principal:** `df.shape`

In [8]:
df.shape

(100, 10)

### Resultado

Nuestra base contiene **100 filas y 10 columnas**, por lo que el resultado es `(100, 10)`.

### `columns`

El atributo `columns` permite conocer los nombres de todas las columnas del DataFrame.

**Código principal:** `df.columns`

In [9]:
df.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8', 'col9',
       'col10'],
      dtype='object')

### Resultado

Nuestra base contiene las columnas `col1` a `col10`.

### `info()`

El método `info()` proporciona información general sobre las columnas, los valores no nulos y los tipos de datos.

**Código principal:** `df.info()`

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    100 non-null    float64
 1   col2    100 non-null    int64
 2   col3    100 non-null    float64
 3   col4    100 non-null    int64
 4   col5    100 non-null    object
 5   col6    100 non-null    object
 6   col7    100 non-null    float64
 7   col8    100 non-null    int64
 8   col9    100 non-null    object
 9   col10   100 non-null    object
dtypes: float64(3), int64(3), object(4)
memory usage: 7.9+ KB

### Resultado

El resultado permite conocer la estructura general de las 100 entradas y 10 columnas de nuestra base.

# 4. Seleccionar columnas

Pandas permite seleccionar una o varias columnas utilizando corchetes `[]`.

Para una columna usamos `df["columna"]`. Para varias columnas usamos una lista dentro de los corchetes, por ejemplo `df[["col1", "col2"]]`.

### Una columna

Para seleccionar una sola columna escribimos su nombre entre comillas.

**Código principal:** `df["col5"]`

In [11]:
df["col5"]

0     B
1     A
2     C
3     A
4     D
     ..
95    B
96    C
97    D
98    A
99    B
Name: col5, Length: 100, dtype: object

### Resultado

El resultado es una Serie de Pandas que contiene todos los valores de `col5`.

### Varias columnas

Para seleccionar varias columnas utilizamos una lista.

**Código principal:** `df[["col1", "col2"]]`

In [12]:
df[["col1", "col2"]]

      col1  col2
0   380.79    49
1   951.21    56
2   734.67    49
3   602.67    21
4   164.46    47
..     ...   ...
95  498.86    43
96  527.51    20
97  433.27    36
98   35.16    37
99  116.81    49

[100 rows x 2 columns]

### Resultado

El resultado es un DataFrame que contiene únicamente las columnas seleccionadas.

### Selección mediante listas

Podemos guardar los nombres de las columnas que queremos seleccionar en una lista y utilizarla después.

**Código principal:** `columnas_seleccionadas = ["col1", "col5", "col10"]`

In [13]:
columnas_seleccionadas = ["col1", "col5", "col10"]
df[columnas_seleccionadas]

      col1 col5  col10
0   380.79    B   Alto
1   951.21    A  Medio
2   734.67    C   Alto
3   602.67    A   Alto
4   164.46    D  Medio
..     ...  ...    ...
95  498.86    B   Bajo
96  527.51    C   Alto
97  433.27    D   Bajo
98   35.16    A   Bajo
99  116.81    B   Bajo

[100 rows x 3 columns]

### Resultado

El resultado contiene únicamente `col1`, `col5` y `col10`.

# 5. Filtrar datos

Filtrar datos significa seleccionar únicamente las filas que cumplen una condición.

Podemos utilizar operadores como `>`, `<`, `>=`, `<=`, `==` y `!=`.

**Código principal:** `df[df["col1"] > 500]`

### Condiciones numéricas

Podemos filtrar una columna numérica mediante una condición.

In [14]:
df[df["col1"] > 500]

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2   734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3   602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
7   867.51    56  55.9     6    A  Norte  0.058     1   No   Bajo
8   605.10    62  40.6     9    A  Oeste  0.395     3   No  Medio
9   710.99    32  42.2     4    A    Sur  0.107     4   Sí  Medio
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
12  834.12    53  50.9     6    A   Este  0.647     3   No   Alto
17  529.51    45  34.0     9    A  Norte  0.260     5   Sí   Bajo
20  615.73    62  63.8     5    D  Oeste  0.280     3   Sí   Alto
25  787.32    61  67.5     6    D  Oeste  0.076     2   No   Alto
27  519.09    47  33.6     5    B   Este  0.417     5   No   Bajo
28  596.49    28   6.8     6    D   Este  0.581     1   No   Bajo
30  611.47    42  49.9     9    D  Norte  0.083     1   No   Alto
33  949.40    18  33.3     5    A    Sur  0.165     2   No  Medio
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
35  810.31    30  64.4     4    A   Este  0.778     2   No   Bajo
38  687.39    56  84.1     4    B  Oeste  0.377     1   No  Medio
41  500.23    44  27.5     4    B   Este  0.829     1   No   Alto
43  910.23    54  56.2     3    D    Sur  0.064     5   Sí  Medio
45  665.90    59  63.1     4    B   Este  0.134     2   Sí   Alto
47  524.87    41  29.8     9    C   Este  0.075     1   Sí   Alto
48  551.24    32  62.8     9    C  Norte  0.692     1   Sí   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
51  777.38    41  26.4     3    D  Oeste  0.913     4   Sí   Bajo
52  940.10    58  72.2     1    A    Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A    Sur  0.726     4   No   Alto
54  601.92    56  23.3     9    C  Oeste  0.757     2   Sí  Medio
55  922.66    19  46.4     9    D  Oeste  0.378     5   No  Medio
62  830.45    40  35.8     7    D   Este  0.757     5   No   Alto
65  547.27    50  23.8     0    C    Sur  0.022     3   Sí  Medio
67  804.18    36  25.7     3    A   Este  0.476     1   No   Alto
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo
70  774.52    43  37.2     2    D  Norte  0.816     2   No  Medio
73  817.31    49  43.3     2    C    Sur  0.792     2   Sí   Bajo
74  709.79    21  56.3    10    A  Norte  0.590     4   Sí  Medio
75  731.72    28  39.1     4    D    Sur  0.480     1   No   Bajo
76  773.56    34  23.0     2    A    Sur  0.421     1   Sí   Bajo
80  864.47    51  39.0     9    C  Norte  0.903     4   No   Alto
81  627.07    23  52.9    10    A  Norte  0.617     2   No   Bajo
86  732.31    50  32.0     6    B  Norte  0.091     4   No   Bajo
87  641.18    26  68.0     0    C   Este  0.726     2   No   Alto
88  888.34    23  52.2     9    B  Oeste  0.547     1   No  Medio
91  716.11    20  21.8     9    C   Este  0.298     2   No  Medio
92  763.18    37  64.5     9    A   Este  0.524     1   No   Bajo
93  565.66    53  42.3     1    C  Oeste  0.698     5   Sí   Alto
94  773.26    36  68.2     2    C  Norte  0.796     4   Sí   Alto
96  527.51    20  44.4     6    C   Este  0.842     2   Sí   Alto

### Resultado

El resultado contiene únicamente las filas donde `col1` es mayor que 500.

### Condiciones categóricas

También podemos filtrar utilizando variables categóricas.

Por ejemplo, podemos seleccionar los registros donde `col6` sea `"Sur"`.

In [15]:
df[df["col6"] == "Sur"]

      col1  col2  col3  col4 col5 col6   col7  col8 col9  col10
0   380.79    49  56.4     1    B  Sur  0.294     5   No   Alto
4   164.46    47  37.4     7    D  Sur  0.737     3   Sí  Medio
6    67.50    40  78.1     9    A  Sur  0.959     3   Sí   Bajo
9   710.99    32  42.2     4    A  Sur  0.107     4   Sí  Medio
11  970.21    46  55.7     4    B  Sur  0.170     1   No   Bajo
13  220.22    30  57.5     8    A  Sur  0.388     3   Sí   Bajo
14  190.01    49  47.8     4    D  Sur  0.229     3   No  Medio
18  437.63    19  51.6     0    C  Sur  0.453     2   No  Medio
24  461.51    61  22.3     0    D  Sur  0.133     4   Sí  Medio
33  949.40    18  33.3     5    A  Sur  0.165     2   No  Medio
39  445.75    23  52.2     9    A  Sur  0.750     2   Sí   Alto
42   44.04    26  49.8     6    D  Sur  0.569     3   No   Bajo
43  910.23    54  56.2     3    D  Sur  0.064     5   Sí  Medio
46  318.59    61  69.5     6    A  Sur  0.014     4   No   Alto
50  969.89    49  49.9     4    D  Sur  0.750     5   No   Bajo
52  940.10    58  72.2     1    A  Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A  Sur  0.726     4   No   Alto
65  547.27    50  23.8     0    C  Sur  0.022     3   Sí  Medio
73  817.31    49  43.3     2    C  Sur  0.792     2   Sí   Bajo
75  731.72    28  39.1     4    D  Sur  0.480     1   No   Bajo
76  773.56    34  23.0     2    A  Sur  0.421     1   Sí   Bajo
85  331.93    33  80.0     2    C  Sur  0.555     2   Sí  Medio
95  498.86    43  47.7     8    B  Sur  0.459     2   Sí   Bajo
99  116.81    49  56.3     4    B  Sur  0.046     5   Sí   Bajo

### Resultado

El resultado muestra únicamente los registros cuya categoría en `col6` es `"Sur"`.

### Varias condiciones

Podemos combinar condiciones utilizando:
- `&` para AND.
- `|` para OR.
- `~` para NOT.

Cuando combinamos condiciones debemos colocar cada una entre paréntesis.

In [16]:
df[(df["col6"] == "Sur") & (df["col5"] != "B")]

      col1  col2  col3  col4 col5 col6   col7  col8 col9  col10
4   164.46    47  37.4     7    D  Sur  0.737     3   Sí  Medio
6    67.50    40  78.1     9    A  Sur  0.959     3   Sí   Bajo
9   710.99    32  42.2     4    A  Sur  0.107     4   Sí  Medio
13  220.22    30  57.5     8    A  Sur  0.388     3   Sí   Bajo
14  190.01    49  47.8     4    D  Sur  0.229     3   No  Medio
18  437.63    19  51.6     0    C  Sur  0.453     2   No  Medio
24  461.51    61  22.3     0    D  Sur  0.133     4   Sí  Medio
33  949.40    18  33.3     5    A  Sur  0.165     2   No  Medio
39  445.75    23  52.2     9    A  Sur  0.750     2   Sí   Alto
42   44.04    26  49.8     6    D  Sur  0.569     3   No   Bajo
43  910.23    54  56.2     3    D  Sur  0.064     5   Sí  Medio
46  318.59    61  69.5     6    A  Sur  0.014     4   No   Alto
50  969.89    49  49.9     4    D  Sur  0.750     5   No   Bajo
52  940.10    58  72.2     1    A  Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A  Sur  0.726     4   No   Alto
65  547.27    50  23.8     0    C  Sur  0.022     3   Sí  Medio
73  817.31    49  43.3     2    C  Sur  0.792     2   Sí   Bajo
75  731.72    28  39.1     4    D  Sur  0.480     1   No   Bajo
76  773.56    34  23.0     2    A  Sur  0.421     1   Sí   Bajo
85  331.93    33  80.0     2    C  Sur  0.555     2   Sí  Medio

### Resultado

El resultado muestra las filas que cumplen simultáneamente que `col6` sea `"Sur"` y `col5` sea diferente de `"B"`.

También podemos utilizar OR:

In [17]:
df[(df["col5"] == "A") | (df["col6"] == "Norte")]

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
2   734.67    49  57.2     2    C  Norte  0.697     5   Sí   Alto
3   602.67    21  63.9     0    A  Norte  0.384     3   Sí   Alto
6    67.50    40  78.1     9    A    Sur  0.959     3   Sí   Bajo
7   867.51    56  55.9     6    A  Norte  0.058     1   No   Bajo
8   605.10    62  40.6     9    A  Oeste  0.395     3   No  Medio
9   710.99    32  42.2     4    A    Sur  0.107     4   Sí  Medio
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
12  834.12    53  50.9     6    A   Este  0.647     3   No   Alto
13  220.22    30  57.5     8    A    Sur  0.388     3   Sí   Bajo
15  191.57    24  52.7     0    D  Norte  0.266     5   No   Alto
16  311.20    39  64.5     9    C  Norte  0.360     2   No   Alto
17  529.51    45  34.0     9    A  Norte  0.260     5   Sí   Bajo
22  299.22    45  59.8     7    A  Norte  0.603     5   Sí   Bajo
23  372.70    45  66.5     4    C  Norte  0.271     2   Sí  Medio
26  207.68    37  35.2     4    C  Norte  0.941     5   Sí   Bajo
29   55.99    45  38.0     2    A  Norte  0.919     5   Sí   Alto
30  611.47    42  49.9     9    D  Norte  0.083     1   No   Alto
31  178.82    56  44.3     2    A  Oeste  0.877     4   No  Medio
33  949.40    18  33.3     5    A    Sur  0.165     2   No  Medio
35  810.31    30  64.4     4    A   Este  0.778     2   No   Bajo
37  106.70    20  21.7     3    A  Norte  0.985     3   No   Bajo
39  445.75    23  52.2     9    A    Sur  0.750     2   Sí   Alto
40  130.82    25  58.1     9    A   Este  0.393     1   No  Medio
44  266.19    50  47.9     0    A   Este  0.037     1   No   Bajo
46  318.59    61  69.5     6    A    Sur  0.014     4   No   Alto
48  551.24    32  62.8     9    C  Norte  0.692     1   Sí   Bajo
49  193.01    49  55.9     5    A  Norte  0.534     3   No   Bajo
52  940.10    58  72.2     1    A    Sur  0.585     2   Sí   Alto
53  895.88    29  56.0     3    A    Sur  0.726     4   No   Alto
56   97.61    20  54.9     2    A  Oeste  0.241     2   No   Bajo
57  204.02    54  57.6     9    C  Norte  0.205     3   No   Alto
59  332.08    19  55.1     7    B  Norte  0.275     3   Sí   Alto
61  278.64    45  73.2     3    D  Norte  0.878     4   Sí  Medio
63  363.19    54  41.0     6    C  Norte  0.047     2   Sí   Alto
66  149.51    18  29.9    10    D  Norte  0.498     3   Sí   Alto
67  804.18    36  25.7     3    A   Este  0.476     1   No   Alto
68   83.81    19  32.8     7    A  Oeste  0.831     5   No   Bajo
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo
70  774.52    43  37.2     2    D  Norte  0.816     2   No  Medio
71  206.73    49  34.6     0    A  Oeste  0.968     1   Sí   Alto
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto
74  709.79    21  56.3    10    A  Norte  0.590     4   Sí  Medio
76  773.56    34  23.0     2    A    Sur  0.421     1   Sí   Bajo
78  364.88    41  26.7     0    D  Norte  0.639     4   Sí   Bajo
79  124.71    22  42.3     7    A  Oeste  0.805     1   Sí   Alto
80  864.47    51  39.0     9    C  Norte  0.903     4   No   Alto
81  627.07    23  52.9    10    A  Norte  0.617     2   No   Bajo
82  337.59    39  41.7     1    A   Este  0.980     3   No  Medio
83   72.92    28  48.1     2    B  Norte  0.608     1   No  Medio
86  732.31    50  32.0     6    B  Norte  0.091     4   No   Bajo
89  477.49    33  52.1     7    A  Norte  0.451     4   Sí   Bajo
92  763.18    37  64.5     9    A   Este  0.524     1   No   Bajo
94  773.26    36  68.2     2    C  Norte  0.796     4   Sí   Alto
97  433.27    36  30.6     3    D  Norte  0.769     3   Sí   Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo

### Resultado

El resultado incluye los registros donde se cumple al menos una de las dos condiciones.

# 6. Ordenar datos

El método `sort_values()` permite ordenar las filas utilizando una o varias columnas.

Por defecto ordena de menor a mayor. Para ordenar de mayor a menor utilizamos `ascending=False`.

**Código principal:** `df.sort_values("col1")`

In [18]:
df.sort_values("col1")

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
42   44.04    26  49.8     6    D    Sur  0.569     3   No   Bajo
58   54.78    34  48.1     0    D   Este  0.251     3   No   Alto
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo

[100 rows x 10 columns]

### Resultado

Los registros quedan ordenados de menor a mayor según `col1`.

### Ejemplo con nuestra base de datos

Podemos ordenar `col1` de mayor a menor.

In [19]:
df.sort_values("col1", ascending=False)

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
69  987.02    61  70.8     1    C  Norte  0.308     4   No   Bajo
11  970.21    46  55.7     4    B    Sur  0.170     1   No   Bajo
50  969.89    49  49.9     4    D    Sur  0.750     5   No   Bajo
34  965.98    44  63.0     8    C  Oeste  0.411     1   Sí   Bajo
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
58   54.78    34  48.1     0    D   Este  0.251     3   No   Alto
42   44.04    26  49.8     6    D    Sur  0.569     3   No   Bajo
98   35.16    37  38.5     9    A  Norte  0.066     3   Sí   Bajo
10   30.38    60  50.2     9    D  Norte  0.336     4   No  Medio
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto

[100 rows x 10 columns]

### Resultado

Los registros con los valores más altos de `col1` aparecen primero.

También podemos ordenar utilizando varias columnas.

In [20]:
df.sort_values(["col10", "col1"])

      col1  col2  col3  col4 col5   col6   col7  col8 col9  col10
72   15.47    23  63.2     0    D  Norte  0.088     1   No   Alto
58   54.78    34  48.1     0    D   Este  0.251     3   No   Alto
29   55.99    45  38.0     2    A  Norte  0.919     5   Sí   Alto
79  124.71    22  42.3     7    A  Oeste  0.805     1   Sí   Alto
66  149.51    18  29.9    10    D  Norte  0.498     3   Sí   Alto
..     ...   ...   ...   ...  ...    ...    ...   ...  ...    ...
88  888.34    23  52.2     9    B  Oeste  0.547     1   No  Medio
43  910.23    54  56.2     3    D    Sur  0.064     5   Sí  Medio
55  922.66    19  46.4     9    D  Oeste  0.378     5   No  Medio
33  949.40    18  33.3     5    A    Sur  0.165     2   No  Medio
1   951.21    56  13.0     9    A  Oeste  0.996     2   Sí  Medio

[100 rows x 10 columns]

### Resultado

Primero se ordena por `col10` y después por `col1` dentro de cada categoría.

# 7. Estadística descriptiva

Las estadísticas descriptivas permiten resumir las variables numéricas de nuestra base.

- `describe()` = resumen estadístico.
- `mean()` = promedio.
- `median()` = mediana.
- `min()` = mínimo.
- `max()` = máximo.
- `std()` = desviación estándar.

### `describe()`

Genera un resumen estadístico de las columnas numéricas.

**Código principal:** `df.describe()`

In [21]:
df.describe()

             col1        col2        col3       col4        col7        col8
count  100.000000  100.000000  100.000000  100.00000  100.000000  100.000000
mean   475.479300   40.650000   48.323000    4.72000    0.493950    2.900000
std    294.514525   13.699056   15.726294    3.26314    0.291855    1.396243
min     15.470000   18.000000    6.800000    0.00000    0.014000    1.000000
25%    201.267500   28.000000   37.350000    2.00000    0.264500    2.000000
50%    469.500000   43.000000   49.900000    4.00000    0.480000    3.000000
75%    732.900000   50.250000   57.525000    8.00000    0.751750    4.000000
max    987.020000   65.000000   84.100000   10.00000    0.996000    5.000000

### Resultado

El resultado incluye cantidad de datos, media, desviación estándar, mínimo, cuartiles y máximo de las variables numéricas.

### `mean()`

Calcula la media o promedio de una columna.

**Código principal:** `df["col1"].mean()`

In [22]:
df["col1"].mean()

np.float64(475.4793000000001)

### Resultado

La media de `col1` se calcula a partir de los 100 registros de nuestra base.

### `median()`

Calcula la mediana de una columna, es decir, el valor central de los datos ordenados.

**Código principal:** `df["col3"].median()`

In [23]:
df["col3"].median()

np.float64(49.9)

### Resultado

El resultado es la mediana de `col3`.

### `min()`

Encuentra el valor mínimo de una columna.

**Código principal:** `df["col1"].min()`

In [24]:
df["col1"].min()

np.float64(15.47)

### Resultado

El resultado es el menor valor registrado en `col1`.

### `max()`

Encuentra el valor máximo de una columna.

**Código principal:** `df["col1"].max()`

In [25]:
df["col1"].max()

np.float64(987.02)

### Resultado

El resultado es el mayor valor registrado en `col1`.

### `std()`

Calcula la desviación estándar de una columna y permite conocer la dispersión de los datos respecto a su media.

**Código principal:** `df["col1"].std()`

In [26]:
df["col1"].std()

np.float64(294.5145254165289)

### Resultado

El resultado muestra la desviación estándar de `col1`.

# 8. Trabajar con variables categóricas

Las variables categóricas contienen diferentes categorías o grupos.

- `value_counts()` = cuenta la frecuencia de cada categoría.
- `unique()` = muestra las categorías diferentes.
- `nunique()` = cuenta cuántas categorías diferentes existen.

### `value_counts()`

Cuenta cuántas veces aparece cada categoría en una columna.

**Código principal:** `df["col5"].value_counts()`

In [27]:
df["col5"].value_counts()

col5
A    34
C    26
D    25
B    15
Name: count, dtype: int64

### Resultado

En nuestra base, `col5` contiene las categorías A, B, C y D y el resultado muestra cuántas veces aparece cada una.

### `unique()`

Muestra los diferentes valores que aparecen en una columna sin repetirlos.

**Código principal:** `df["col6"].unique()`

In [28]:
df["col6"].unique()

array(['Sur', 'Oeste', 'Norte', 'Este'], dtype=object)

### Resultado

En `col6` podemos observar las diferentes categorías presentes en la base.

### `nunique()`

Cuenta cuántos valores diferentes existen en una columna.

**Código principal:** `df["col6"].nunique()`

In [29]:
df["col6"].nunique()

4

### Resultado

El resultado indica cuántas categorías diferentes existen en `col6`.

# 9. Agrupar datos

El método `groupby()` permite dividir los datos en grupos utilizando una variable categórica y posteriormente calcular estadísticas para cada grupo.

Esto es especialmente útil para responder preguntas como:

- ¿Cuál es el promedio de `col1` para cada categoría de `col5`?
- ¿Cuántos registros existen en cada categoría?
- ¿Cuál es el valor máximo y mínimo de cada grupo?

**Código principal:** `df.groupby("col5")`

### Promedios por categoría

Podemos utilizar `groupby()` junto con `mean()` para calcular el promedio de una variable numérica para cada categoría.

In [31]:
df.groupby("col5")["col1"].mean()

col5
A    471.190882
B    474.602000
C    501.510769
D    454.765200
Name: col1, dtype: float64

### Resultado

El resultado muestra el promedio de `col1` para cada categoría de `col5`.

### Conteos por categoría

También podemos contar cuántos registros existen en cada categoría utilizando `size()`.

In [32]:
df.groupby("col6").size()

col6
Este     21
Norte    33
Oeste    22
Sur      24
dtype: int64

### Resultado

El resultado muestra la cantidad de registros que pertenece a cada categoría de `col6`.

### Agregaciones

Con `agg()` podemos calcular varias estadísticas al mismo tiempo.

En este ejemplo obtenemos el promedio, máximo, mínimo y cantidad de registros de `col1` para cada categoría de `col10`.

In [33]:
df.groupby("col10")["col1"].agg(["mean", "max", "min", "count"])

             mean     max    min  count
col10
Alto   480.194412  940.10  15.47     34
Bajo   473.109722  987.02  35.16     36
Medio  472.979000  951.21  30.38     30

### Resultado

El resultado es una tabla donde cada fila representa una categoría de `col10` y las columnas contienen diferentes estadísticas de `col1`.

# 10. Crear y modificar columnas

Podemos crear nuevas columnas a partir de las variables existentes.

La sintaxis general es:

`df["nueva_columna"] = ...`

### Ejemplo con nuestra base de datos

Crearemos una nueva columna llamada `col1_mas_col3` sumando los valores de `col1` y `col3`.

In [34]:
df["col1_mas_col3"] = df["col1"] + df["col3"]
df[["col1", "col3", "col1_mas_col3"]].head()

     col1  col3  col1_mas_col3
0  380.79  56.4         437.19
1  951.21  13.0         964.21
2  734.67  57.2         791.87
3  602.67  63.9         666.57
4  164.46  37.4         201.86

### Resultado

La nueva columna contiene, para cada fila, la suma de `col1` y `col3`.

# 11. Extra: combinar operaciones

Una de las ventajas de Pandas es que podemos combinar varias operaciones para responder preguntas más específicas.

En lugar de utilizar los comandos de manera aislada, podemos construir expresiones que primero filtren, después seleccionen y finalmente ordenen los datos.

**Objetivo:** dejar de pensar en comandos aislados y comenzar a construir soluciones utilizando varias operaciones de Pandas.

In [35]:
df[df["col1"] > 500][["col1", "col5", "col6", "col10"]].sort_values("col1", ascending=False)

      col1 col5   col6  col10
69  987.02    C  Norte   Bajo
11  970.21    B    Sur   Bajo
50  969.89    D    Sur   Bajo
34  965.98    C  Oeste   Bajo
1   951.21    A  Oeste  Medio
33  949.40    A    Sur  Medio
52  940.10    A    Sur   Alto
55  922.66    D  Oeste  Medio
43  910.23    D    Sur  Medio
53  895.88    A    Sur   Alto
88  888.34    B  Oeste  Medio
7   867.51    A  Norte   Bajo
80  864.47    C  Norte   Alto
12  834.12    A   Este   Alto
62  830.45    D   Este   Alto
73  817.31    C    Sur   Bajo
35  810.31    A   Este   Bajo
67  804.18    A   Este   Alto
25  787.32    D  Oeste   Alto
51  777.38    D  Oeste   Bajo
70  774.52    D  Norte  Medio
76  773.56    A    Sur   Bajo
94  773.26    C  Norte   Alto
92  763.18    A   Este   Bajo
2   734.67    C  Norte   Alto
86  732.31    B  Norte   Bajo
75  731.72    D    Sur   Bajo
91  716.11    C   Este  Medio
9   710.99    A    Sur  Medio
74  709.79    A  Norte  Medio
38  687.39    B  Oeste  Medio
45  665.90    B   Este   Alto
87  641.18    C   Este   Alto
81  627.07    A  Norte   Bajo
20  615.73    D  Oeste   Alto
30  611.47    D  Norte   Alto
8   605.10    A  Oeste  Medio
3   602.67    A  Norte   Alto
54  601.92    C  Oeste  Medio
28  596.49    D   Este   Bajo
93  565.66    C  Oeste   Alto
48  551.24    C  Norte   Bajo
65  547.27    C    Sur  Medio
17  529.51    A  Norte   Bajo
96  527.51    C   Este   Alto
47  524.87    C   Este   Alto
27  519.09    B   Este   Bajo
41  500.23    B   Este   Alto

### Resultado

En esta expresión:
1. Filtramos los registros donde `col1` es mayor que 500.
2. Seleccionamos `col1`, `col5`, `col6` y `col10`.
3. Ordenamos los resultados de mayor a menor según `col1`.

El resultado es una tabla con los registros que cumplen la condición, mostrando únicamente las columnas seleccionadas.

### Ejemplo final

También podemos combinar filtrado y agrupación para responder una pregunta más específica: ¿cuál es el promedio de `col1` para cada categoría de `col5`, considerando únicamente los registros donde `col1` es mayor que 500?

In [36]:
df[df["col1"] > 500].groupby("col5")["col1"].mean()

col5
A    773.411250
B    709.067143
C    701.319286
D    775.260000
Name: col1, dtype: float64

### Resultado

La expresión primero filtra los registros con `col1 > 500` y después calcula el promedio de `col1` para cada categoría de `col5`.

Esto demuestra cómo podemos construir soluciones combinando diferentes operaciones de Pandas.